# Spring properties
spring:
  application:
    name: tugasbm  # Identify this application
  freemarker:
    enabled: false     # Ignore Eureka dashboard FreeMarker templates
  thymeleaf:
    cache: false       # Allow Thymeleaf templates to be reloaded at runtime
    #prefix: classpath:/web-server/templates/    # Trailing / mandatory
    # Template location for this application onlya
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tugas_bm2
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  cloud:
    refresh:
      enabled: false



# Map the error path to error template (for Thymeleaf)
error.path: /error

# HTTP Server
server:
  port: 

  